### ISSUE TITLE
Slice bounds out of range panic error

### ISSUE THREAD

**Issue by Usman2ABN** [gitleaks/gitleaks#1141] opened 2023-04-07 14:07 UTC
**Describe the bug**
Panic error when invoking docker/binary with -v flag along with rule file having rule with  only PATH parameter and no regex.
Example rule:
[[rules]]
	id = "Apache-Htpasswd-File"
	description = "Apache Htpasswd File"
    	path = '''(?i)[\/\\]{1}\.?htpasswd$'''
	tags = []

**To Reproduce**
The bug can be reproduced via the following steps:

- Download one of the docker image/binary listed below
- Invoke the gitleaks image with the required flags, **especially -v (verbose)**
example:
docker run -v /Users/foo/config:/tmp/config
           -v /Users/foo/source:/tmp/source
           zricethezav/gitleaks:latest detect
           -c /tmp/config/rules/gitleaks_rules.toml
           -s /tmp/source
           -f json
           -r /tmp/report.json
           -v
           --no-banner
           --no-git
Test_data: 

**Expected behavior**
To print findings information on the console.

**Screenshots**
<img width="1007" alt="Screenshot 2023-04-06 at 19 48 56" src="https://user-images.githubusercontent.com/113449186/230405751-f1fe8199-a974-428c-b80a-befc9a612306.png">

**Basic Info (please complete the following information):**
 - OS: Macbook Pro 2021
    OS: Ventura 13.2
    Chip: Apple M1 Pro
    Cores: 8
    Firmware version: 8419.80.7
This has not been tested yet on Linux or Windows machines. Hence, unclear if the bug would manifest there as well.
 - Gitleaks Version: 
    * 8.15.0
    * 8.15.1
    * 8.15.2
    * 8.15.3
    * 8.15.4
    * 8.16.0
    * 8.16.1
    * latest

**Additional context**

cc @zricethezav

**Comment by rgmz** [comment] 2023-04-12 04:08
The issue _seems_ to be caused by path matches having no `f.Line`:
https://github.com/gitleaks/gitleaks/blob/839f114f2b2ca9429300e545aa5c93a2caf2e3d8/detect/utils.go#L127-L131

However, I am not able to consistently reproduce it based on that description alone. I am guessing it has to do with how `matchInLineIDX` is calculated.

----

Consider the following rule and files:

**Rule**
```yml
[[rules]]
id = "file-keytab"
description = "Keytab file"
path = '''\.keytab$'''
tags = ["file", "pem"]
```

**Files**
```sh
$ touch /tmp/empty.keytab
$ echo "Hello, world" > /tmp/small.keytab
$ echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nDuis pharetra rhoncus mauris vel elementum.\nEtiam et consequat sapien, ut molestie ipsum.\n" > /tmp/long.keytab
```

On the latest version of GitLeaks (and repo HEAD) only the second file panics.
```sh
$ /home/me/gitleaks detect --no-banner --config ./gitleaks.toml --no-git --verbose --source /tmp/empty.keytab
12:02AM INF scan completed in 409µs
12:02AM INF no leaks found
$ /home/me/gitleaks detect --no-banner --config ./gitleaks.toml --no-git --verbose --source /tmp/small.keytab
panic: runtime error: slice bounds out of range [32:0]

goroutine 22 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0xc000098a80, 0xb}, 0x1, 0x1, 0x0, 0x0, {0x0, 0x0}, {0xc0000b9200, 0x20}, ...}, ...)
	/home/me/detect/utils.go:136 +0x1572
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0xc000098a80, 0xb}, 0x1, 0x1, 0x0, 0x0, {0x0, 0x0}, {0xc0000b9200, ...}, ...})
	/home/me/detect/detect.go:616 +0x3d8
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
	/home/me/detect/detect.go:506 +0x2e5
github.com/fatih/semgroup.(*Group).Go.func1()
	/Users/323249706/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/Users/323249706/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x25b
$ /home/me/gitleaks detect --no-banner --config ./gitleaks.toml --no-git --verbose --source /tmp/long.keytab
12:02AM INF scan completed in 631µs
12:02AM WRN leaks found: 1
```

**Comment by rgmz** [comment] 2023-04-24 15:50
@Usman2ABN My PR was merged so should be fixed in the latest release (8.16.3).

**Comment by rgmz** [comment] 2023-06-15 13:54
@zricethezav I'm pretty sure this can be closed.

**Closed** 2023-06-15 14:05 UTC
Labels: bug

**Comment by Usman2ABN** [comment] 2023-06-15 15:37
Thank you, this has been resolved.
