### ISSUE TITLE
gitleaks protect command doesn’t ignore the secrets mentioned in .gitleaksignore file

### ISSUE THREAD

**Issue by pbhuva-splunk** [gitleaks/gitleaks#1100] opened 2023-02-15 08:52 UTC
When running the below command, the secrets already added in `.gitleaksignore` file are also getting detected.
```
gitleaks protect --staged -v --redact
```
Also, the below command is not following baseline-path argument and secrets are getting detected even if it is already present in base line file.
```
gitleaks protect --staged -v --redact –-baseline-path gitleaks-baseline-path.json -–report-path gitleaks-results.json
```

So, Both ways to ignore specific key or secret is not working.

**Steps to reproduce issue while using `.gitleaksignore` file:**
1. Add a dummy file having secrets and add into staging.
2. Run  ```gitleaks protect --staged -v --redact``` command, to show the secret is getting detected.
3. Add fingerprint for the file in `.gitleaksignore` file.
4. Again run gitleaks protect --staged -v --redact command.

**Expected Behaviour:**
- The secret should be allowed when added to `.gitleaksignore` file.

**Actual Behavior:**
- The secret is not allowed when added to `.gitleaksignore` file.

**Steps to reproduce issue while using baseline file:**
1. Add a dummy file having secrets and add into staging.
2. Run ```gitleaks detect --source . -v --no-git --report-path gitleaks-report.json``` command to create a baseline.
3. Run ```gitleaks protect --staged --baseline-path gitleaks-report.json --report-path gitleaks-report1.json -v``` to use baseline file to ignore the secrets.

**Expected Behaviour:**
- The secret should be allowed.

**Actual Behavior:**

- The secret is not allowed.

**Comment by mjcc30** [comment] 2023-03-01 18:11
same problem for me :/

**Comment by RafaelFigueiredo** [comment] 2023-03-14 18:43
same problem here too

**Comment by RafaelFigueiredo** [comment] 2023-03-14 18:51
I think the problem is that protect --staged is not dealing well with fingerprint without the git hash.
When I ran `gitleaks protect --staged` I got a fingerprint without get starting git hash, which makes sense as the file is not committed yet, I add those finger prints to .gitleaksignore and nothing works. 
My workaround was uninstall pre-commit, commit the files I need, ran `gitleaks detect --verbose` to get the fingerprint with git hash, then I add to .gitleaksignore and reinstall pre-commit.

**Comment by zricethezav** [comment] 2023-03-14 19:19
I'll try and get some eyes on this soon, sorry for the delay

**Comment by RafaelFigueiredo** [comment] 2023-03-15 22:01
@zricethezav do you mind if I try to contribute? I really like golang and that will be an opportunity to study the codebase and  start on the open-source world.

**Comment by zricethezav** [comment] 2023-03-15 22:07
@RafaelFigueiredo of course! That would be greatly appreciated

**Closed** 2023-06-15 14:02 UTC
Labels: bug
