### ISSUE TITLE
Gitleaks: version 8.21.0 Failing with Custom gitleaks.toml

### ISSUE THREAD

**Issue by ektosgit** [gitleaks/gitleaks#1570] opened 2024-10-15 06:58 UTC
Hello GitLeaks Team, we have a problem with Gitleaks version 8.21.0 it now fails to use the custome gitleaks.toml. The only error we receive is:

FTL Failed to load config error="CSCAN0030: [[rules.allowlists]] must contain at least one check for: commits, paths, regexes, or stopwords"
##[error]Execution errors occured. See log for details.
Finishing: Gitleaks Scan

Scan configuration: 
[command]C:\Agents\BuildServer-Agent01\_work\_tool\gitleaks\8.21.0\x64\gitleaks.exe detect --config=C:\Agents\BuildServer-Agent01\_work\3862\s/.gitleaks.toml --source=C:\Agents\BuildServer-Agent01\_work\3862\s --redact --report-format=sarif --report-path=C:\Agents\BuildServer-Agent01\_work\3862\b\Report\GitLeaks.sarif --no-git --exit-code=99

**Comment by rgmz** [comment] 2024-10-15 07:35
Assuming you're using the [Gitleaks Azure DevOps task](https://marketplace.visualstudio.com/items?itemName=Foxholenl.Gitleaks), this should have been fixed by https://github.com/JoostVoskuil/azure-devops-gitleaks/pull/92.

**Comment by iamludal** [comment] 2024-10-15 09:42
Another problem with version 8.21.0 is that it seems like some fingerprints that are included in the `.gitleaksignore` file are not ignored anymore. As a result, the scan fails even if the detected secrets are ignored. It seems to happen on some of `generic-api-key` types only (but not all).

**Comment by serge18** [comment] 2024-10-15 10:38
Any updates here? Predefined configs are not working for me.

**Comment by rgmz** [comment] 2024-10-15 11:11
@iamludal can you provide an example of what you mean? The logic for `.gitleaksignore` wasn't touched AFAIK.

**Comment by zricethezav** [comment] 2024-10-15 11:15
> Any updates here? Predefined configs are not working for me.

need more context

**Comment by iamludal** [comment] 2024-10-15 11:42
> @iamludal can you provide an example of what you mean? The logic for `.gitleaksignore` wasn't touched between 8.20.1 -> 8.21.0 AFAIK.

I had a CI/CD run with version 8.21.0 that detected 41 of my secrets for which the fingerprints exist in the `.gitleaksignore` file. When I tried to rollback to version 8.20.1, it worked again, without making any other changes to the repo. This happened to a repository in the company I work for.

**Comment by zricethezav** [comment] 2024-10-15 11:50
Example?

**Comment by rgmz** [comment] 2024-10-15 11:57
> > I had a CI/CD run with version 8.21.0 that detected 41 of my secrets for which the fingerprints exist in the `.gitleaksignore` file. When I tried to rollback to version 8.20.1, it worked again, without making any other changes to the repo. This happened to a repository in the company I work for.
>
> Example?

If you can't provide a specific example, can you provide specific information about this to help pinpoint the issue?

- How many secrets were you expecting it to detect? 
- Are the secrets detected/not detected in v8.21.0 all from one rule, or multiple?
- Are the rules from your config, an extended config, or are you using the default config?
- Are the detections obvious placeholders or in paths that should be ignored?

**Comment by rgmz** [comment] 2024-10-15 13:38
OH! I think the root cause is #1559.

Older versions of go-gitdiff were incorrectly reporting the merge commit SHA instead of the commit SHA (#1333). You'll likely need to update the fingerprints your `.gitleaksignore` to use the new (correct) commit SHAs.

**Comment by iamludal** [comment] 2024-10-15 14:23
Thanks for your reply, indeed the commit SHA is different. I should have noticed that the overall fingerprint has changed...

**Comment by zricethezav** [comment] 2024-10-15 14:24
Thanks for tracking that down @rgmz. @ektosgit is your original concern resolved? @iamludal what about you (different issue)?

**Comment by zricethezav** [comment] 2024-10-15 21:58
release notes updated https://github.com/gitleaks/gitleaks/releases/tag/v8.21.0

**Closed** 2024-10-15 21:58 UTC
Labels: bug

**Comment by riosengineer** [comment] 2024-11-19 14:14
Hey @zricethezav @rgmz I am also getting this error, and I am not sure why. Would you be able to point me in the right direction? 

I previously was using v8.20.1 and started getting this error with v8.21.2. My `.gitleaks.toml` hasn't changed, and was working fine. I do seem to have at least one of the checks mentioned on the first reply. I am not using the ADO Task. 

My gitleaks.toml config:

```text
title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true
[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api|token|secret|client|passwd|password|auth|access)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([0-9a-z\-_.=]{10,150})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
secretGroup = 1
entropy = 3.5
keywords = [
    "key","api","token","secret","client","passwd","password","auth","access",
]
[rules.allowlist]

[allowlist]
    description = "Allowlisted files"
    paths = [
    '''gitleaks.toml''',
    '''(?i)(.*?)(png|jpeg|jpg|gif|doc|docx|pdf|bin|xls|xlsx|pyc|zip)$'''
    ]
    regexTarget = "line"
    regexes = [ # Regexes for false positives
        '''tenant-id'''
    ]
```

Any ideas would be appreciated! Thank you.

**Comment by riosengineer** [comment] 2024-11-19 14:38
For anyone who also has this error, I fixed mine by changing my `.gitleaks.toml` [allowlist] to [rules.allowlists].

**Comment by rgmz** [comment] 2024-11-19 15:15
@riosengineer your issue was having an empty `[rules.allowlist]` heading. Allowlists need to have a condition, otherwise they're nil.

> For anyone who also has this error, I fixed mine by changing my .gitleaks.toml [allowlist] to [rules.allowlists].

`[rules.allowlists]` doesn't exist as a valid config key. You'd need to either remove the empty heading, or add some conditions to it.

**Comment by iamludal** [comment] 2024-11-20 08:13
> Thanks for tracking that down @rgmz. @ektosgit is your original concern resolved? @iamludal what about you (different issue)?

Hi, we have updated the fingerprints as indicated in the release notes of v8.21.0, thanks for your help. Maybe it should have been a major release just to be sure that other users are not impacted.

**Comment by riosengineer** [comment] 2024-11-20 09:25
> @riosengineer your issue was having an empty `[rules.allowlist]` heading. Allowlists need to have a condition, otherwise they're nil.
> 
> > For anyone who also has this error, I fixed mine by changing my .gitleaks.toml [allowlist] to [rules.allowlists].
> 
> `[rules.allowlists]` doesn't exist as a valid config key. You'd need to either remove the empty heading, or add some conditions to it.

Thank you for your reply. Will check it out again but for now, I am all good!
