### ISSUE TITLE
Generic rule false negative when secret is only letters

### ISSUE THREAD

**Issue by weineran** [gitleaks/gitleaks#1231] opened 2023-07-14 22:47 UTC
**Describe the bug**
I have a Jwt__Token with only upper and lowercase letters. It is a secret, but the generic api rule doesn't catch it. It looks like this:
```
"Jwt__Token" = "SomeTokenXyzabc"
```

**To Reproduce**
* Create a file with the above snippet of code
* Run gitleaks to scan the file
* Gitleaks reports "no leaks found"

**Expected behavior**
Gitleaks should detect `Jwt__Token` as a secret

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: windows 10
 - Gitleaks Version: 8.17.0

**Additional context**
Hi buddy 👋 

cc @zricethezav

**Comment by weineran** [comment] 2023-07-14 23:18
This one is actually strange because when I paste the generic api key regex into regex101 and paste the above secret in, it tells me there is a match. But when I run gitleaks on a file containing the secret, it doesn't find the secret. 🤔 
![image](https://github.com/gitleaks/gitleaks/assets/5898785/2b995374-c101-4624-9dc8-a90438ee099c)

**Comment by rgmz** [comment] 2023-07-14 23:20
That string probably isn't passing the Entropy check:

https://github.com/gitleaks/gitleaks/blob/06db3b91d7495a39caf0d922aef5fee0118e7538/config/gitleaks.toml#L509

**Comment by weineran** [comment] 2023-07-14 23:25
@rgmz I initially had the same thought, but apparently it has shannon entropy of 3.64
https://planetcalc.com/2476/
![image](https://github.com/gitleaks/gitleaks/assets/5898785/005fbc64-5863-4830-a17c-20e66f387fbe)

(Also the real secret in the wild, which I didn't post above has even higher entropy)

**Comment by weineran** [comment] 2023-07-14 23:31
Another weird thing: If I add a number in there anywhere, then gitleaks detects it. That is, this gets correctly flagged as a secret:
```
"Jwt__Token" = "SomeTokenXyzab1"
```

**Comment by weineran** [comment] 2023-07-14 23:33
I can't find any problem with the regex itself. Starting to wonder if it's a bug in the regex library... 🤔

**Comment by zricethezav** [comment] 2023-07-18 16:05
Not a bug w/ the regex library: 

https://github.com/gitleaks/gitleaks/blob/f0dcd4d9cfe9e9f3e588acb1fd0aaad2e4328ea8/detect/detect.go#L327-L355

Basically `SomeTokenXyzab` isn't convincing enough. Generic secrets must contain digits otherwise too many false positives would be flagged. Closing this issue

**Closed by zricethezav** 2023-07-18 16:05 UTC
Labels: bug
