### ISSUE TITLE
Getting a "could not write error=" when trying to generate report

### ISSUE THREAD

**Issue by weedobaledo** [gitleaks/gitleaks#1021] opened 2022-10-20 15:19 UTC
I'm trying to use gitleaks in an Azure DevOps pipeline. I install and run gitleaks using Docker. 

Here's the command I use:
docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --report-path leaks/leaks.txt --source /path --log-level=debug

Here's the log of the error I get.
Status: Downloaded newer image for zricethezav/gitleaks:latest
docker.io/zricethezav/gitleaks:latest

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

2:58PM DBG no gitleaks config found in path /path/.gitleaks.toml, using default gitleaks config
2:58PM DBG executing: /usr/bin/git -C /path log -p -U0 --full-history --all
2:58PM INF 401 commits scanned.
2:58PM DBG Note: this number might be smaller than expected due to commits with no additions
2:58PM INF scan completed in 475ms
2:58PM WRN leaks found: 11
2:58PM FTL could not write error="open leaks/leaks.txt: no such file or directory"

I've already verified that I can write to that directory by creating a dummy file.

**Basic Info (please complete the following information):**
 - OS:  Ubuntu 20.04.5
 - Gitleaks Version: 8.15.0

cc @zricethezav

Appreciate your help

**Comment by weineran** [comment] 2022-10-20 17:23
> I've already verified that I can write to that directory by creating a dummy file.

Can you post the commands you used to verify this? Did you connect to the container using `docker exec -it ...`

**Comment by weedobaledo** [comment] 2022-10-20 17:48
I did not exec to the container, but did these commands:

mkdir leaks
echo “Overwriting the existing text in the file” >> $(pwd)/leaks/leaks.txt
ls -la $(pwd)/leaks/leaks.txt
cat $(pwd)/leaks/leaks.txt

**Output**:

-rw-r--r-- 1 vsts docker 48 Oct 20 15:35 /home/vsts/work/1/s/leaks/leaks.txt

Overwriting the existing text in the file

**Comment by weineran** [comment] 2022-10-20 18:34
Looks like some confusion over volume mapping. To troubleshoot, I recommend connecting to the container and poking around.
- Run the stopped container interactively using a shell:
```
docker run -v $(pwd):/path -it --entrypoint=sh zricethezav/gitleaks
```
* Once you're in the container, check if the `leaks` directory exists in the working directory. I believe your working directory will be `/` and you will find that the `leaks` directory does not exist there.
* Check if the leaks directory exists elsewhere. Based on the info you provided, if it exists anywhere, I suspect it will be in the `/path` directory.
* Once you find the `leaks` directory, exit the docker container.
* Re-run your docker command with the correct `--report-path`.
    * e.g. I suspect you will find that `--report-path /path/leaks/leaks.txt` will work.
    * If all else fails, you should be able to simply write the report to the `/path` directory like this:
    `--report-path /path/leaks.txt`

**Comment by weedobaledo** [comment] 2022-10-20 22:46
@weineran - first, thanks very much for the detailed and descriptive explanation.

Unfortunately, I'm still stuck with this issue.

- As I'm using a Microsoft provided Azure DevOps container, I'm handicapped with what I can and can't do.
- I don't think I have the ability to exec into the Docker container without writing an entrypoint script. The only access I have to the shell in an Azure DevOps container is through the pipeline.
- So I tried your Hail Mary solution.

 docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --report-path /path/leaks.txt --source /path --log-level=debug

Now I get a permission denied. I tried to think of solution to do a chmod or chown in the container volume, but none worked.

**Output**:

Digest: sha256:ebf35c0373d275e0a65e424a35343a9c243bff848fc6c3340c410f59e6616cc8
Status: Downloaded newer image for zricethezav/gitleaks:latest
docker.io/zricethezav/gitleaks:latest

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:39PM DBG no gitleaks config found in path /path/.gitleaks.toml, using default gitleaks config
10:39PM DBG executing: /usr/bin/git -C /path log -p -U0 --full-history --all
10:39PM INF 401 commits scanned.
10:39PM DBG Note: this number might be smaller than expected due to commits with no additions
10:39PM INF scan completed in 618ms
10:39PM WRN leaks found: 11
10:39PM FTL could not write error="open /path/leaks.txt: permission denied"

In the absence of generating and storing a report file, can I just get the results in the stdout somehow?

Thanks again...

**Comment by weineran** [comment] 2022-10-21 02:58
I'm not familiar with Azure DevOps pipelines, so maybe someone else from the community can jump in and help here...?

In the meantime, one more idea. Based on the output you posted further above, it looks like the target directory is owned by the `vsts` user, so you could try re-running your docker run command with `--user=vsts` or maybe try `--user=root`

Let me know if that works

**Comment by weineran** [comment] 2022-10-21 03:01
Regarding dumping the report to stdout, not sure it's possible but you could try `--report-path=/dev/stdout`

**Comment by weedobaledo** [comment] 2022-10-21 12:09
**Output with --user=root**

Digest: sha256:ebf35c0373d275e0a65e424a35343a9c243bff848fc6c3340c410f59e6616cc8
Status: Downloaded newer image for zricethezav/gitleaks:latest
docker.io/zricethezav/gitleaks:latest

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:52AM DBG no gitleaks config found in path /path/.gitleaks.toml, using default gitleaks config
11:52AM DBG executing: /usr/bin/git -C /path log -p -U0 --full-history --all
11:52AM ERR [git] fatal: detected dubious ownership in repository at '/path'
11:52AM ERR [git] To add an exception for this directory, call:
11:52AM ERR [git] 
11:52AM ERR [git] 	git config --global --add safe.directory /path
11:52AM INF 0 commits scanned.
11:52AM DBG Note: this number might be smaller than expected due to commits with no additions
11:52AM ERR  error="git error encountered, see logs"
11:52AM WRN partial scan completed in 163ms
11:52AM WRN no leaks found in partial scan
-rw-r--r-- 1 root root 3 Oct 21 11:52 leaks.txt
ls: cannot access '/path/leaks.txt': No such file or directory
##[error]Bash exited with code '2'.

Looks like it was able to create the file leaks.txt. But scanning failed.

**Output with --user=vsts**

latest: Pulling from zricethezav/gitleaks
213ec9aee27d: Already exists
f42be66b2ee9: Pulling fs layer
130ff4f6a09a: Pulling fs layer
a7f1b9c03428: Pulling fs layer
a7f1b9c03428: Verifying Checksum
a7f1b9c03428: Download complete
130ff4f6a09a: Verifying Checksum
130ff4f6a09a: Download complete
f42be66b2ee9: Download complete
f42be66b2ee9: Pull complete
130ff4f6a09a: Pull complete
a7f1b9c03428: Pull complete
Digest: sha256:ebf35c0373d275e0a65e424a35343a9c243bff848fc6c3340c410f59e6616cc8
Status: Downloaded newer image for zricethezav/gitleaks:latest
docker.io/zricethezav/gitleaks:latest
docker: Error response from daemon: unable to find user vsts: no matching entries in passwd file.
time="2022-10-21T11:55:33Z" level=error msg="error waiting for container: context canceled"
ls: cannot access 'leaks.txt': No such file or directory
ls: cannot access '/path/leaks.txt': No such file or directory
##[error]Bash exited with code '2'.
Finishing: Secrets Scan



**Output with /dev/stdout**

latest: Pulling from zricethezav/gitleaks
213ec9aee27d: Already exists
f42be66b2ee9: Pulling fs layer
130ff4f6a09a: Pulling fs layer
a7f1b9c03428: Pulling fs layer
a7f1b9c03428: Verifying Checksum
a7f1b9c03428: Download complete
130ff4f6a09a: Download complete
f42be66b2ee9: Verifying Checksum
f42be66b2ee9: Download complete
f42be66b2ee9: Pull complete
130ff4f6a09a: Pull complete
a7f1b9c03428: Pull complete
Digest: sha256:ebf35c0373d275e0a65e424a35343a9c243bff848fc6c3340c410f59e6616cc8
Status: Downloaded newer image for zricethezav/gitleaks:latest
docker.io/zricethezav/gitleaks:latest

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

12:01PM DBG no gitleaks config found in path /path/.gitleaks.toml, using default gitleaks config
12:01PM DBG executing: /usr/bin/git -C /path log -p -U0 --full-history --all
12:01PM ERR [git] fatal: detected dubious ownership in repository at '/path'
12:01PM ERR [git] To add an exception for this directory, call:
12:01PM ERR [git] 
12:01PM ERR [git] 	git config --global --add safe.directory /path
12:01PM INF 0 commits scanned.
12:01PM DBG Note: this number might be smaller than expected due to commits with no additions
12:01PM ERR  error="git error encountered, see logs"
12:01PM WRN partial scan completed in 71.1ms
12:01PM WRN no leaks found in partial scan
[]
ls: cannot access 'leaks.txt': No such file or directory
ls: cannot access '/path/leaks.txt': No such file or directory

**Comment by weineran** [comment] 2022-10-21 16:56
@weedobaledo I'll take a closer look at all this info this weekend.

Out of curiosity, are you able to reproduce any/all of these issues when running the docker container on your local machine? Or are these only reproducible in your Azure DevOps pipeline?

**Comment by weineran** [comment] 2022-11-30 05:35
I just became aware of this Gitleaks pipeline on the marketplace: https://marketplace.visualstudio.com/items?itemName=Foxholenl.Gitleaks

Might be worth checking out?

**Comment by jfgsilva** [comment] 2023-12-09 16:01
Hi, 

so I did some more digging, the issue in fact is related to uid:gid mappings between host and container when writing to mounted volumes and the container user is non-root.

gituser could be kept and adding a specific uid, but portability would be an issue

**Comment by PipeItToDevNull** [comment] 2023-12-22 02:04
Rootless Podman has this issue. I use `--user=root` to avoid it for now. 

Thanks

**Closed** 2024-02-01 14:23 UTC
Labels: bug
